//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionMusical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int idCancion { get; set; }
        public bool activa { get; set; }
        public int artista_id { get; set; }
        public Nullable<int> album_id { get; set; }
        public int categoria_id { get; set; }
        public string clave { get; set; }
        public int genero_id { get; set; }
        public string nombre { get; set; }
        public string observacion { get; set; }
        public int prioridad { get; set; }
        public string radio { get; set; }
        public string tiempo { get; set; }
        public string tiempoIntro { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artista Artista { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
