//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionMusical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elemento
    {
        public int idElemento { get; set; }
        public bool activo { get; set; }
        public string clave { get; set; }
        public string comentario { get; set; }
        public string nombre { get; set; }
        public string radio { get; set; }
    }
}
