//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionMusical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elemento
    {
        public int idElemento { get; set; }
        public bool activo { get; set; }
        public string clave { get; set; }
        public string comentario { get; set; }
        public string nombre { get; set; }
        public string radio { get; set; }
    }
}
